language: node_js
node_js:
- 'node'
git:
  depth: 10
before_install:
- npm install -qg bower gulp-cli
- npm install -q
- bower install --force
- bower install --force
script: gulp ci
sudo: false
env:
  global:
    - SAUCE_USERNAME=angular-ui-mask
    - SAUCE_ACCESS_KEY=b4b4d64e-4188-4cae-a91c-29214a389c8a
deploy:
  provider: npm
  email: adrien.crivelli@gmail.com
  api_key:
    secure: BO798oqVC/vfFllHuEfFR+A1j0VEWbsLUkEkHq4bZMUO626VCd1NwEzboDcVI6xROcNJ9RiAZ6BhG9oQTBdCshENxCbESL3qjEj3q+9UJwKnp2QttdTxXojajKxrAG5hkSpnICSiZpQIbudRphx9gc8ul/ETc7MGnptAhkF7ecIk4C9jF9E7czW4mu68+N4Nx/NWI4cjAHSE88KRHuF5O/tbbOn5txhuQCwex34DBLEevGlT3GF7V7NFlrDW7OzYDh2MwqRreITLoZJ9NuMfH0uA1bIfQgn4/Uh+5J27WNVcJr6PYWLcA0Fo48EK1OuxsJX1AmNSEy2QBmCE5hcifFdpigrusKemBLZbhO5TCcmdWXyIYz/8pH6XnHs48DFTUYosjdfhtAQ65y6Zv4wGxpYNtviagApefGOOQHfRsig3l2adXQriTctVtoUDJ9TfdG/gaIrhztKKJJ8RkBBEAs/acAW3iPgn5w4aT8pGj4cKcubEFYrJjmU0vQfUCsE+brr/iE6JGZ/Ga5d3A2n512n+yicQULFtNqZRXwjqMfA6+eHo0ImzJP9bP1E39Z5u1DT2BfegBH9UrLaIPc7xK8saoxed7mrczlnzbvO0+ibFsHP5uQZJ0jyVZ/V25UDsIXp1IlL4hNZ6dwfAu/7qir3UdcsM6+iqMUR4WqMiaRg=
  on:
    tags: true
    repo: angular-ui/ui-mask
